version: '3'

services:
  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespwtest
    ports:
      - "5555:5432"

  play-app:
    image: yundoisl/book-store:0.0.1
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    links:
      - postgresql:postgreshost